export const defaultRow = {
    month: '',
    variantIndex: 0,
    rowKey: '',
    depositSavings: 0,
    depositInvestments: 0,
    isDepositSavingsManual: false,
    isDepositInvestmentsManual: false,
    isManualFromFirestore: false,
    totalSavings: 0,
    totalInvestments: 0,
    isTotalSavingsManual: false,
    isTotalInvestmentsManual: false,
    totalSaved: 0,
    interestReturn: 0,
    investmentReturn: 0,
    grandTotal: 0,
    commentary: '',
    isActive: true,
    isAlt: false,
    goal: null,
};
